### ISSUE TITLE
Option to manually controll reference counting on threaded objects

### ISSUE THREAD

**Issue by chibisuke** [krakjoe/pthreads#403]
While I know why the requirement exists that you need to keep a reference outside of any threaded scope, this is pretty tedious to work with, and in many cases required one to fall back to using $GLOBALS[] as a container for those references. 

Now I'd like to know what you think of allowing manual control of the refcount for a threaded object so you do not need to use such workarounds. 

example:
```php
<?php
class A extendeds Thread {
        function run() {
                $this->a = (new Threaded)->addRef();
                //do something here
                
                $this->a->release();
                unset($this->a);
        }
}
?>
```

addRef() and release() would only be callable from the thread that did the new.

what do you think? did I miss somthing?
any downsides (except the fact that ppl doing PHP arn't usually used to take care of their resources)?

**Comment by Doggie52** [comment]
Intuitively, a member of a Thread shouldn't need to be referenced from outside the scope of the same Thread in order to stay alive, no?

I think perhaps guides or tips are needed so people can better understand how to build valid, multithreaded applications. @krakjoe you say that PHP coders aren't used to doing research on how to 'best' build something: this is an area of PHP where surprisingly little "correct" literature exists. The examples in the manual are so obviously copy-pasted from one function to another and the entries themselves include very little, if any, explanation.

**Comment by krakjoe** [comment]
We can't change the rules; You are responsible for the objects you create, think of the properties table of a Threaded object as only a weak store - because that's what it is, that's what it must remain.

However, I do recognize there is some value in being able to control refcounts for edge cases, it should not be the normal way to operate.

I have exposed enough for this to be possible in 7, will backport to 5 today.

Please try to stick to the rules, if you don't know what you are doing with reference counting, then please don't touch it. getting my help when you're writing code that doesn't follow the rules is going to be hard ... you have been warned ...
