### ISSUE TITLE
Refs, statics and complexity ?

### ISSUE THREAD

**Issue by zelgerj** [krakjoe/pthreads#420]
Hi Joe,

i just wanted to discuss the handling of statics and refs as we want to be compatible with your current and upcoming versions without having a modified version forked all the time...

#### Refs
I know there is a good reason for not being responsible holding refs that are not real refs like you modified the code here https://github.com/krakjoe/pthreads/commit/5a39d3ed83d046573a7ba55ed6ce425e218198e9.

For us it would be a big advantage to have that responsibility in case of having more control about what is being freed or holded at a certain point. I know we can do this easily by creating refs in global context as described here https://github.com/krakjoe/pthreads/issues/361 but doing this looks a bit strange and feels very uncommon when coding things. Maybe it would be possible to introduce NullPointer-Exceptions? Maybe it makes sense to keep it configurable via ini properties `pthreads.refs_keep = 1`? Do you have an suggestion to that? 

#### Statics
The other problem we encountered is that just simple property types are kept in static objects when inherit all to threads. I know there is a "trick" by just not inherit those static classes as mentioned here https://github.com/krakjoe/pthreads/issues/271 but this is also a performance thing... Our appserver can not preload all needed classes for certain thread contexts when it is not possible to inherit them... We have already refactored our code for that, but we still can not use 3rd party libs as they are... I know that there are many bugs coming from statics... but don't you think it would make sense to get it configurable as well? have no problems encountered yet, so for us it would be cool to have another ini property like `pthreads.statics_inherit_complex = 1` ?

#### Complexity
I noticed that you want to prevent the php userland from any complexity when using threads. That is in fact a good idea to keep first steps smooth... but for us as an infrastructure software completely written in php that is normally written in c it is not enough and we highly wanted to have the possibility for complex things to do with your library at your own risk. `pthreads.complex = 1` ? :)

Let me know what you think. i'am really looking forward on that!

Thanks for your time! Cheers
Johann

**Comment by smolinari** [comment]
I am interested in knowing the possibilities here too. Although the "complex" stuff sounds like it needs more detail. :+1: 

Scott

**Comment by krakjoe** [comment]
Refs:     this is a solved problem in 7
Statics:  there should be many less bugs coming from statics in 7, the same rules still apply (static = thread-local), I'm extremely reluctant to add ini settings, this raises the wtf per minute rate when systems are configured differently for whatever reason. The safest thing to do is what we are doing ..
Complexity: if you mean you want to do things like leave out locking, it's not going to happen.

If there is more to say, say it ... closing, but not necessarily end of conversation.

**Comment by zelgerj** [comment]
Ok thanks Joe!

**Comment by krakjoe** [comment]
Some improvements there @wagnert, I'll leave addRef/delRef in, but you shouldn't need it now.

https://github.com/krakjoe/pthreads/blob/seven/tests/immutable-threaded-members.phpt
https://github.com/krakjoe/pthreads/blob/seven/tests/norefs.phpt

**Comment by 2072** [comment]
Awesome! This will make things so much easier, thank you for this great and elegant idea :-)

**Comment by wagnert** [comment]
That will make things easy when switching to PHP 7 and pthreads 3 :) Thanks Joe

**Comment by SirSnyder** [comment]
@krakjoe that's not good. It must be possible to change a class property($this->t as example)! I've build a complete runtime environment on your paradigm "you are responsable of the objects you create", so please keep this.

**Comment by krakjoe** [comment]
@SirSnyder don't panic, here is a banana to eat while you read some stuff I'm about to say :banana: ...

There are extremely good reasons for these changes, they have  the side effect that you no longer have to care about references, but they have a *much more important* purpose, that I think if you knew about you would think differently.

If you ```git checkout babd11a560eb5ff48ad9bec3d8cfd477a3f8c8fa``` and run the following code:

	<?php
	class Member extends Threaded {
		public function method() {
			return $this;
		}
		public function condition() {
			return true;
		}
	}

	class Test extends Thread {

		public function __construct(Member $member) {
			$this->member = $member;
		}

		public function run() {
			while ($this->member->condition()) {
				var_dump($this->member->method()	);
			}
		}
	}

	$member = new Member();
	$test = new Test($member);
	$test->start();
	$test->join();
	?>

in gdb, setting a breakpoint at ```pthreads_base_ctor```.

In case you can't be bothered, I'll tell you what you will see; You will see an infinite number of objects being constructed, stored in the object store, having properties initialized and all the junk that makes an object work.

If you set breakpoints at other points such as those to acquire locks, you would see just how complex it was to store a threaded object (which is thread safe already) as a member. Putting up with all of that for a stdClass or some other object is not so bad, it provides us safety so we can put up with the enormous cost.

If you run the code against the current head of seven branch, you would see base_ctor run twice for each object, one object for each context. You would see locks avoided reading these objects after the first read, and you would see it is *extremely fast* to operate on Threaded objects now.

I appreciate that you listened well to my advice, but what if, I gave you new advice ??

It's quite simple really, synchronize and mutate objects rather than set different references and everything will go at the speed of light ...

I'd be surprised if there is any code that will not require refactoring for v3, so given that, is it really so complex to follow a new (better) rule ?

I'm not a fan of switches that change the way things work, it means I have to give many explanations that are much more complex, and it means everyone has to be aware of those switches if they don't want any wtfs.

**Comment by SirSnyder** [comment]
@krakjoe thanks for the banana and your response. Yes, the handling and storage of threaded objects is complex, no question, I'm with you. Our applications based on pthreads are complexe as well and they work fine until right now. Nearly all objects extend Threaded. We dont have to care that much about object creation and references. Instead of new we use ::create() all over the place. Create() retrieves and provides an object instance from primary thread(pooled), which acts like a little generations garbage collection and handles/observes all instances.

```
<?php
class O extends Threaded {
	public function run(){}
}
class T extends Thread {
	public function __construct() {
		$this->t = new O(); # now immutable
		$this->t->set = true;
		$this->s = new stdClass();
	}
	
    public function run(){
		var_dump($this->t, $this->s, $this);
	}
}
```
Here we have a little nitty gritty example, but how should that work in a real world application with tens or hundreds of properties containing complexe/threaded data structures too? I use Threaded as a threaded array to save more threaded objects, that won't be possible in future, right?

```
<?php
	$objData = Threaded::create();
	$objData ['xxx'] = ... new Threaded object ...;
	....
	$objData ->clear(); // exception
```

So far we have to destroy unused instances explicit by calling ->destroy() in our apps. That is a bit ugly and annoying but ok to get threading in such a way for php. The perfect way would be a normal ref counting behavior in combination with your newly added getRefCount method, so our little GC could collect and destroy/drop all unreferenced instances automatically.

**Comment by krakjoe** [comment]
I'm still working on this, we need the speed of immutability as an option, and I think the default ... but what we can do is have volatile members, for whom immutability rules do not apply ... 

I will update when I've done some stuff ...

**Comment by SirSnyder** [comment]
That sounds like a good solution, thanks Joe

**Comment by krakjoe** [comment]
https://github.com/krakjoe/pthreads/commit/f2841c324205a352fd72c2e9728e5ee32815a569

Use case covered, right ?

**Comment by SirSnyder** [comment]
Looks good, you're the best!
