### ISSUE TITLE
Mutex::trylock is not working with multiply threads

### ISSUE THREAD

**Issue by TheSaturn** [krakjoe/pthreads#440]
Hello! I hope this problem with my hands, but it looks like a bug.
I create 5 threads and call Mutex::trylock in every thread. Three threads get true, two get false. Let's see:
```php
<?php
class SharedData extends Stackable {
    public function run() {}
}
class T extends Thread {
    public function __construct($test){
        $this->test = $test;
    }
    public function run(){
        $mutex = $this->test['mu'];
        $cond = $this->test['co'];
        if(Mutex::trylock($mutex))
        {//Why I entere here more then 1 time?
            echo Thread::getCurrentThreadId()."Hello, I'm is your problem \n";
            sleep(3);
            Cond::broadcast($cond);
            Mutex::unlock($mutex);
            flush();
        }
        else {
            echo Thread::getCurrentThreadId()."wait \n";
            flush();
            Cond::wait($cond, $mutex);
            echo Thread::getCurrentThreadId()."unlocked \n";
            flush();
            //Cond::signal($cond);
        }
    }
}
$mutex = Mutex::create();
$cond = Cond::create();
$arrayToSort = new SharedData();
$arrayToSort['mu'] = $mutex;
$arrayToSort['co'] = $cond;
while(@$i++ < 5){
    $ts[]=new T($arrayToSort);
}
foreach($ts as $thread)
{
    $thread->start();
}
foreach($ts as $t)
    $t->join();
print_r($arrayToSort);
Cond::destroy($cond);
Mutex::destroy($mutex);
```
Output:
```
140034187917056Hello, I'm is your problem 
140034179524352wait 
140034171131648Hello, I'm is your problem 
140034162149120wait 
140034153166592Hello, I'm is your problem 
140034179524352unlocked 
140034162149120unlocked 
```
if 50 threads: 26 get true, 24 false
PHP 5.6.8 (cli) (built: Apr 23 2015 19:32:21) 
About pecl.php.net/pthreads-2.0.10
Release Date          2014-10-01 06:24:45
Release Version       2.0.10 (stable)
API Version           2.0.10 (stable)
Last Modified         2015-04-24 14:29
Archlinux
What am I doing wrong?

**Comment by krakjoe** [comment]
The code is wrong, you have not synchronized the start of the threads, in addition you have only tried to ensure that no more than one thread enters the critical section *at a time*, not that only one thread enters for all of time, which seems to be what you are expecting.

Mutex and Cond are not really intended for general consumption, they are useful to have around but tricky to program with, might I suggest you use the builtin object monitor utility functions (wait/notify/synchronized) rather than Cond/Mutex directly.

Happy to provide a better example code (when I have a free moment) if you can explain properly what you are trying to do.

Going to close the bug, because there's no bug here, just misuse, but that doesn't finish the conversation ;)

**Comment by TheSaturn** [comment]
Hmm.I'm expecting that several threads call trylock at a time, but  mutexes should provide atomic lock/unlock/trylock, am I right?
in addition: I try to wrap all code in run with $this->synchronized(); It is not help me.
