### ISSUE TITLE
::kill returns false

### ISSUE THREAD

**Issue by Khelle** [krakjoe/pthreads#483]
Hi everyone,
I am using Pthreads for a longer of time right know, but today I ran into a problem I cannot find answer nor by myself nor searching with google, so I decided to write here.
I tried using Thread::kill() method to force Thread to stop execution before it has completed it's workload, but it does not seem to work. It always returns bool(false), and continue exectuion. Below I present a simple snippet of code, that should close immediately by calling $wrapper->kill() in process scope or $this->kill() in thread scope, but it does not.

```
class ThreadWrapper extends Thread
{
    public function run()
    {
        echo "ThreadWrapper->run()" . PHP_EOL;

        for ($i=0; $i<5; ++$i)
        {
            echo "ThreadWrapper->loop()" . PHP_EOL;
            var_dump($this->kill());
            sleep(1);
        }
    }
}

$wrapper = new ThreadWrapper();

$wrapper->start(PTHREADS_INHERIT_NONE);
var_dump($wrapper->kill());
```

Above code returns:
```
ThreadWrapper->run()
bool(false)
ThreadWrapper->loop()
bool(false)
ThreadWrapper->loop()
bool(false)
ThreadWrapper->loop()
bool(false)
ThreadWrapper->loop()
bool(false)
ThreadWrapper->loop()
bool(false)
```

The machine configuration is Windows 7 with PHP5.4.10 and pthreads 2.0.10. Previously I was using 2.0.8 and had the same problem. What can I do to solve this despite changing OS, since code is required to work on Windows too?

**Comment by krakjoe** [comment]
It is not guaranteed to work, various things need to be supported and they simply aren't on windows.

You should not write code that relies on the ability to kill another thread, is it not graceful.

Please put requests for help with code on stackoverflow, to reduce repetition and to help others, thanks :)

**Comment by Khelle** [comment]
Thank you for your answer. I know I should not rely on Thread::kill() to stop threads, but I need to have a way to force it to stop them if for some reason standard IPC stop command I am using fails to deliver message for some reason like thread being locked in infite loop or another. Is there any way to enforce killing thread from process level?

**Comment by chibisuke** [comment]
Well on windows the low level APIs work in a pretty nasty way:
a killed thread doesn't free its resources. The resources,library ect.  
will remain locked any are never freed again, so you're wasting memory.
additionally keep in mind that any mutexes/conditionals/critical 
sections the thread holds will remain locked, which can cause a deadlock 
later in the execution; if the thread is currently allocating memory, 
the heap-lock will not be freed either, which means the next time PHP is 
allocationg memory, you end up in a deadlock.

You actually don't want this to work that way... because it means your 
application *will* fail, and it will fail randomly without any means of 
debugging.

as for pthreads..... from the man page:
*Pthreads-w32*only supports signal number 0, which does not send any 
signal but causes*pthread_kill*to return an error if/thread/is not valid.
*Pthreads-w32*does not implement signals yet and so these routines have 
almost no use except to prevent the compiler or linker from 
complaining.*pthread_kill*is useful in determining if the thread is a 
valid thread, but since many threads implementations reuse thread IDs, 
the valid thread may no longer be the thread you think it is, and so 
this method of determining thread validity is not portable, and very 
risky.*Pthreads-w32*from version 1.0.0 onwards implements pseudo-unique 
thread IDs, so applications that use this technique (but really 
shouldn't) have some protection.

So this function is simply not implemented in the underlaying library. 
Most likely because of aforementioned problems.
