### ISSUE TITLE
Latest release message

### ISSUE THREAD

**Issue by smolinari** [krakjoe/pthreads#492]
Hi @krakjoe,

> This release disables pthreads in all but the CLI SAPI.

> After many years of advising that multi-threading at the frontend doesn't make sense, I'm promoting the advice to hard and fast fact.

Could you expand on that a bit more please? I am sort of perplexed threads is being reduced to CLI only as default, when so many are using it for frontend multi-threaded programming. (Especially with projects like [icicle.io with their concurrency component](https://github.com/icicleio/concurrent) and [appserver.io](http://appserver.io/) with their PHP multi-threaded application server). 

A multithreaded PHP application server is also what a good number of experienced and professional programmers ([including Fabien Potencier](https://youtu.be/gpNbmEnRLBU?t=640) "avoid trashing things, that can be reused"!!!) think is the way to get PHP much deeper into the realms of enterprise applications. It might not be the perfect way, but the potential to improve performance to "share some things" is there and seen. You are basically saying this potential is something useless to go after and all the great efforts made already are for naught in one fell swoop. I don't get it. I'd like to understand better, as I also am (was?) betting on multi-threaded PHP applications too. 

Scott

**Comment by smolinari** [comment]
I just happened to read an answer of yours in an issue, which just popped up. (Strange how things like that can happen sometimes). It led me to this. 

http://blog.krakjoe.ninja/2014/10/but-is-it-web-scale.html

I can understand the argumentation, but you must also admit, PHP with its shared nothing architecture and in the cases of a large application, tends to cause a lot of waste in the request / response lifecycle. It causes a lot of good work by the application to be built, then only to be destroyed at the end of the cycle. There is a lot of work that could be held in memory within a threaded context to save for further use. I can "concurrently" use that held in memory data effectively avoiding the painful bootstrapping process normal PHP forces me to do with each request. That alone is a major pain removal, which pthreads allows. 

So, I say, pthreads for the frontend win! :smiley: :+1: 

Scott

**Comment by smolinari** [comment]
Who else can come up with reasons why pthreads is cool for the frontend and make Joe a believer that his fantastic efforts are far greater and better than "just for CLI"?
 
Scott

**Comment by krakjoe** [comment]
appserver using threads is arguably sensible, this change doesn't break that. They use threads to implement their own architecture, I've not heard anyone advise that users should create their own threads, if I do, I'll correct them, because it would be silly advice.

If the kind of work you want icicle to do requires multi-processing or multi-threading, then that doesn't belong at the frontend of a web application either, the author is well aware, he's a friend of mine.

PHP is a shared nothing architecture, each context has it's own copy of the interpreter, and all user code. *Nothing* is shared, the same goes for pthreads, they don't share memory like conventional threads because that simply cannot work in a shared nothing architecture. Anyone talking about making gains there doesn't know enough about it to be authoritative. Something within Zend would need to fundamentally change for it to be sensible to talk about using threads in the context of Zend and web servers, and it would be a stupid change. PHP is reliable at scale, and easy to scale, precisely because it is shared nothing.

There's no sense in which I'm saying don't use pthreads, I'm only saying that you need to use it properly, that there is simply no way for me to support the execution of multithreaded applications housed inside other multithreaded applications with no means of making either environment properly aware or prepared for the other in a robust way. This commit only acknowledges what has always been the case.

This is not going to change.

**Comment by smolinari** [comment]
> appserver using threads is arguably sensible, this change doesn't break that. 

I figured as much, and I guess that is all I needed to know. Thanks.

Scott
