### ISSUE TITLE
Projects using SAPI don't work because of the SAPI whitelist

### ISSUE THREAD

**Issue by hfedcba** [krakjoe/pthreads#557]
Hey,

I understand your reasoning behind the SAPI whitelist. The problem is, all projects using PHP's SAPI won't work with pthreads. I'm programming a home automation interface software (Homegear) and use PHP as scripting engine. Devices can be programmed using XML and PHP (see for example https://github.com/Homegear/Homegear-OpenWeatherMap/blob/master/OpenWeatherMap.xml). I use your great PHP extension to enable event handling. The problem now is, everybody who wants to compile the project by himself needs to patch the pthreads source to add Homegear to the whitelist. As I'm probably not the only one with this problem, would it maybe make sense to convert the whitelist into a blacklist? Or would it be possible to "register" projects to your whitelist?

Cheers,

Sathya

**Comment by krakjoe** [comment]
I used a white list because it's more likely that pthreads shouldn't be loaded than it should, there can only be a minority of SAPIs that are genuinely safe using pthreads.

The idea was exactly that people who have SAPI's who know they are safe can put in a PR, and I will take a cursory look at the SAPI before accepting the PR.

If you are sure that your SAPI is safe, open such a PR, include link to your source code.

**Comment by hfedcba** [comment]
ok, thanks for the quick response. I'm currently reworking the script engine. As soon as I'm done, I will open the pull request. Thank you!
