### ISSUE TITLE
Method isWaiting

### ISSUE THREAD

**Issue by hartois** [krakjoe/pthreads#586]
* PHP: 7.0.5
  * pthreads: 3.1.7dev
  * OS: Fedora 23 x86

```
class thr extends Thread{
	public function run(){
		var_dump($this->isWaiting());
	}
}
$thr = new thr();
$thr->start();
```

Result: 
PHP Fatal error:  Uncaught Error: Call to undefined method thr::isWaiting() in /var/www/online/test.php:19
Stack trace:
#0 [internal function]: thr->run()
#1 {main}
  thrown in /var/www/online/test.php on line 19

In pthreads v3 method isWaiting() was removed?

**Comment by hiteshbalyan** [comment]
getting same problem with PHP 7 with pthreads v3

**Comment by krakjoe** [comment]
It was removed.

**Comment by hartois** [comment]
What to use instead?

**Comment by krakjoe** [comment]
It was removed because there is a flaw in the logic of a program that tries to determine if another object is waiting; Because of the way waiting actually works, a context may detect that an object is waiting while the object is concurrently awoken.

Write code that does not need to make these kind of checks, it was a very bad API ... I was trying to make it easy ... I made a mistake ....
