### ISSUE TITLE
Memory leak on new Thread object

### ISSUE THREAD

**Issue by kovacsrobi77** [krakjoe/pthreads#625]
Environment
==========

  * PHP: 7.0.11 x64
  * pthreads: 3.1.6 x64
  * OS: Windows10x64 and ubuntu 15.05

Summary
======
Memory resource still 32Mb after threads ended and emptyed.

Reproducing Code
==============

<?php

class test_class extends Thread
{
	function run()
	{
	}
}

$i=0;
while ($i!=10000)
{
	$i++;
	$thread = new test_class();
	//$thread->start(PTHREADS_INHERIT_NONE);
	$thread->start();
	$thread->join();
	$thread = null;
	echo "i: ".$i."\n";
}
sleep(6);
$thread = null;
sleep(2);

Expected Output
=============
Low memory use.

Actual Output
============
Big amount of memory used.

**Comment by krakjoe** [comment]
This is not a bug, but a side effect of the way the allocator for Zend works; it allocates a chunk of memory from the system, but does not release that memory back to the system up to memory_limit but retains it in a pool of available memory. It does this because it's faster to allocate from pooled memory than to request from the system allocator.
