### ISSUE TITLE
PHP Fatal error: Unable to start pthreads module 

### ISSUE THREAD

**Issue by AlexSayHello** [krakjoe/pthreads#626]
Environment
==========

  * **PHP:** 7.0.11 x64 ZTS VC14
  * **pthreads:** 3.1.6-7.0 vc14 x64
  * **OS:** Windows 10 x64
  * **Server:** IIS 10.0.14393.0 via FastCGI SAPI Module

Summary
======

Hello.

I have performed a clean install of PHP on a development machine. I used last stable releases of PHP and pthread, availables on their respective websites.

I followed the installation steps included in the README, I added the dll extension to the folder and I added the dll pthreadVC2 to the root directory of PHP. Finally, change the settings in php.ini and restart the IIS server.

I have tried to load a simple script with `phpinfo()`.

Thanks.

Actual Output
============
* IIS returns 500 Internal Server Error with the following info:
   * **Module:** FastCgiModule
   * **Notification:** ExecuteRequestHandler
   * **Error Code:**  0xfffffffe
* Windows Event Viewer is recording these errors with the following info:
    * **Provider:**  PHP-7.0.11
    * **Event ID:** 4
    * **EventData:** PHP Fatal error: Unable to start pthreads module ("PATH\php-cgi.exe")

**Comment by SaitamaSama** [comment]
The `pthreads` module is only available under the `CLI SAPI`, which is also mentioned under the Readme.

And since you are using the `CGI SAPI` it cannot be accessed. :wink:

**Comment by AlexSayHello** [comment]
Oh, right, sorry, skip this part of the documentation.

Well, I understand the reasons developer. But it's a real shame, I really like to have parallel processing in my project. I have taken a project with an odd structure, to render a page, it uses a kind of modules, similar to the Components, with an HTML template, scope, services injection and all those things. Modules are created, configurated, executed and rendered in a secuencial form (a loop). I thought it would parallelize the execution of each method with this extension.

**Comment by wagnert** [comment]
Probably have a look at http://appserver.io, which allows you to use threads in your web application. It comes with a out-if-the-box multithreaded PHP 5.6 runtime and also have binaries that'll run on windows :)

**Comment by AlexSayHello** [comment]
Thanks, did not know about that. I'll take a look and propose to use it.

**Comment by cavo789** [comment]
One question please, if I correctly understand, a web application using pthreads (in my case a web scanner app, on my localhost machine) can't continue to use pthreads under PHP 7.   

And if so, should we fully rewrite our code or is there, neverthless, a way to continue to have threads in a web application ?   My file scan application needs to continue to work like this since I've an interface with ajax and a lot (really a lot) of javascript functions.

(extra info : this application is a virus scan.  I need to scan as fast as possible (=> need threads) and display to the user files and let him to determine if, yes, it's a virus or not (false positive).  Based on his decision, he can delete the virus, edit the file and remove the dangerous part, blacklist the file and so on so the need of a user interface is important).

Thanks a lot for your answers.
