### ISSUE TITLE
Pool::collect is not called for the last thread.

### ISSUE THREAD

**Issue by Idobrev** [krakjoe/pthreads#670]
Environment
==========

  * PHP: PHP 7.1.1 (cli) (built: Jan 26 2017 12:51:39) ( ZTS DEBUG )
  * pthreads: latest from master
  * OS: linux Debian 8 

Reproducing Code
==============

```
<?php
$pool = new Pool(1);
$i = 1;

while ($i <= 10) {
    $pool->submit(new class($i) extends Thread implements Collectable{
        public $id;
        private $garbage = false;

        public function __construct($id) {
            $this->id = $id;
        }

        public function run() {
            sleep(1);
            printf(
                "Hello World from %d\n", $this->id);
            $this->worker->potato = 'I got some data' . $this->id;
            $this->setGarbage();
  
        }

        public function setGarbage() {
            $this->garbage = true;
        }

        public function isGarbage(): bool {
            return $this->garbage;
        }

    });
    $i++;
}       
    
while ($pool->collect(function($work){
    printf(
        "Collecting %d\n", $work->id);
    return $work->isGarbage();
})) continue;
var_dump($pool);
$pool->shutdown();
?>
```

This is what we should be getting if the collect method is being called.

Expected Output
=============

```
Hello World from 1
Collecting 1
Hello World from 2
Collecting 2
Hello World from 3
Collecting 3
Hello World from 4
Collecting 4
Hello World from 5
Collecting 5
Hello World from 6
Collecting 6
Hello World from 7
Collecting 7
Hello World from 8
Collecting 8
Hello World from 9
Collecting 9
Hello World from 10
Collecting 10
object(Pool)#1 (5) {
  ["size":protected]=>
  int(1)
  ["class":protected]=>
  string(6) "Worker"
  ["workers":protected]=>
  array(1) {
    [0]=>
    object(Worker)#3 (1) {
      ["potato"]=>
      string(16) "I got some data10"
    }
  }
  ["ctor":protected]=>
  NULL
  ["last":protected]=>
  int(1)
}
```
As you can see below however the collect method is not called for the last thread.

Actual Output
============
```
Hello World from 1
Collecting 1
Hello World from 2
Collecting 2
Hello World from 3
Collecting 3
Hello World from 4
Collecting 4
Hello World from 5
Collecting 5
Hello World from 6
Collecting 6
Hello World from 7
Collecting 7
Hello World from 8
Collecting 8
Hello World from 9
Collecting 9
object(Pool)#1 (5) {
  ["size":protected]=>
  int(1)
  ["class":protected]=>
  string(6) "Worker"
  ["workers":protected]=>
  array(1) {
    [0]=>
    object(Worker)#3 (1) {
      ["potato"]=>
      string(16) "I got some data9"
    }
  }
  ["ctor":protected]=>
  NULL
  ["last":protected]=>
  int(1)
}
Hello World from 10
```

**Comment by SirSnyder** [comment]
collect() starts before all tasks are done. remove the sleep() call

**Comment by Idobrev** [comment]
Removed the sleep call and now this happens.
```
Hello World from 1
Hello World from 2
Hello World from 3
Hello World from 4
Collecting 1
Collecting 2
Collecting 3
Collecting 4
Hello World from 5
Collecting 5
Hello World from 6
Collecting 6
Hello World from 7
Collecting 7
Hello World from 8
Collecting 8
Hello World from 9
Collecting 9
Hello World from 10
object(Pool)#1 (5) {
  ["size":protected]=>
  int(1)
  ["class":protected]=>
  string(6) "Worker"
  ["workers":protected]=>
  array(1) {
    [0]=>
    object(Worker)#3 (1) {
      ["potato"]=>
      string(17) "I got some data10"
    }
  }
  ["ctor":protected]=>
  NULL
  ["last":protected]=>
  int(1)
}
```

I still cant see the "Collecting 10". Also, could you elaborate on how to get the data out of the pool's workers? Since I can't access them the only method seems to be the collect method, but that method.....

**Comment by Idobrev** [comment]
Also If I understand correctly all threads should be finished before I call $pool->collect. How do I make the calling context wait for all threads to finish?

**Comment by tpunt** [comment]
I think I understand your problem, @Idobrev. Just a few points before I come on to it:
 - You don't need to implement the `Collectable` interface - it is already implemented on the `Threaded` class (as of pthreads v3).
 - You don't need to define a custom garbage collection mechanism in your case, and will not need to in the vast majority of cases (as of pthreads v3).
 - The collector cannot collect tasks that haven't yet been executed, so unless you have some special requirements for garbage collecting, then you can simply always returning `true` from the collector callback.

This gives:
```php
<?php
$pool = new Pool(1);
$i = 1;

while ($i <= 10) {
    $pool->submit(new class($i) extends Thread {
        public $id;

        public function __construct($id) {
            $this->id = $id;
        }

        public function run() {
            sleep(1);
            printf(
                "Hello World from %d\n", $this->id);
            $this->worker->potato = 'I got some data' . $this->id;
        }
    });
    $i++;
}       
    
while ($pool->collect(function($work){
    printf("Collecting %d\n", $work->id);
    return true;
})) continue;
var_dump($pool);
$pool->shutdown();
```

Now, as you have mentioned above, when the collector is executing whilst there are still tasks to be run, the final task does not seem to be collected (preventing you from fetching its data). This looks like a bug to me. A workaround to your problem could be to pass in a `Threaded` object to store any data from the tasks being executed in the pool, so that you can make use of this object after the pool has finished executing. For example:
```php
$pool = new Pool(1);
$i = 1;
$data = [];

while ($i <= 10) {
    $data[$i] = new Threaded();
    $pool->submit(new class($i, $data[$i]) extends Thread {
        public $id;
        private $data;

        public function __construct($id, Threaded $data) {
            $this->id = $id;
            $this->data = $data;
        }

        public function run() {
            printf("Hello World from %d\n", $this->id);
            $this->data->value = 'I got some data' . $this->id;
        }
    });
    $i++;
}

while ($pool->collect()); // block until all tasks have finished executing

foreach ($data as $d) {
    var_dump($d->value);
}
```

> Also If I understand correctly all threads should be finished before I call $pool->collect

No, the `Pool::collect()` method simply cleans up the tasks that have finished executing (the ones on the garbage stack). This can be done whilst there is still work in the pool (as you have seen above).

**Comment by Idobrev** [comment]
Hey @tpunt,

That was really helpful, Thanks, mainly because information for pthreadv3 is so scarce on the net. There are ton of examples for previous version that do not work anymore. Also, the more I read, the more I get to understand how threads work ( since I haven't had much experience with them ). So one more question. What If I want to extract an array type of data out of the thread. So in the previous example it become something like this:

```
.....
public function run() {
            printf("Hello World from %d\n", $this->id);
            $this->data->value = array (  " I got some data {$this->id}" ) ;
        }
......
```
This results:
`PHP Fatal error:  Uncaught RuntimeException: pthreads detected an attempt to connect to an object which has already been destroyed in /media/theBox2/programs/php/examples/sample4.php:28`


Now I know for a fact ( because I've been doing a shit ton of tests now ) that this would create an array which will get destroyed once the thread is killed ( since I guess, because we are still in the context of the thread and all references to that array are collected by the gc?? ), however if we create a volatile array it will not be destroyed.  For example:
If we do this ( creating a volatile array ) by implicit cast that will result a proper output.
```
public function run() {
            printf("Hello World from %d\n", $this->id);
            $this->data->value = (array) array (  " I got some data {$this->id}" ) ;
        }
```
This results:
```
array(1) {
  [0]=>
  string(19) " I got some data 10"
}
```
Which is a proper array which has 1 element in it with key 0 and points to that string. My question is why is it not an `array( array ( 0 =>  " I got some data {$this->id}"  ))` ? And why is it preserved after we explicitly cast it to an array ( I can also create an object and put that array into a property in the object and it will also be preserved )? 
Sorry to bother you with all of these, but I am trying to figure things out...

**Comment by tpunt** [comment]
@Idobrev pthreads automatically stores arrays as `Threaded` objects (specifically of the `Volatile` class, as of pthreads v3), due to normal arrays not being safe to manipulate from multiple contexts. This default behaviour can be overridden by explicit casting so that the array literal will actually be a PHP array (and not a `Volatile` object). (pthreads internally employs some hacks to bypass storing arrays as a `Volatile` objects on a property write accesses by checking that the previous opcode of the currently executing opline is an array cast.)

> that this would create an array which will get destroyed once the thread is killed

As far as I know, `Threaded` objects are attached to the context in which they are created in. So when the array is created as a `Volatile` object in your above script, it will be attached to the context of that thread. When that thread is either joined or killed, the created `Volatile` object gets destroyed with it.

You also seem to have the terminology backwards with respect to normal arrays (i.e. PHP arrays) and pthreads' `Volatile` (object) arrays. :)

> My question is why is it not an array( array ( 0 => " I got some data {$this->id}" ))

When you cast an array to an array, it doesn't create a new array that wraps around the casted array. [This is normal PHP behaviour](https://3v4l.org/GHe2i).

**Comment by Idobrev** [comment]
@tpunt 
Ah so we are creating a volatile array and we are casting as a normal array, which somehow bypasses the thread safety and allows several contexts to write to it. So is that the proper behavior, I mean can I use that to get the data out of the thread? Is that safe enough?

**Comment by tpunt** [comment]
> Ah so we are creating a volatile array and we are casting as a normal array

Not really. The array isn't firstly being created as a `Volatile` object that then gets casted to an array. The array cast effectively dictates whether the property value will be  stored as either a normal PHP array, or a `Volatile` pthreads object.

> which somehow bypasses the thread safety and allows several contexts to write to it.

`Threaded` objects (such as `Volatile`) are safe to manipulate from multiple contexts because they employ monitors internally to safely read and write to their properties. This prevents multiple contexts attempting to read and/or write at the same time (causing data corruption).

> So is that the proper behavior, I mean can I use that to get the data out of the thread? Is that safe enough?

As far as I know, it is safe to do this.

**Comment by Idobrev** [comment]
Thank you man! :+1:

**Comment by tpunt** [comment]
To answer the first question, the garbage collector for pthreads is not deterministic. It should therefore not be relied upon to fetch data. The way mentioned above (passing in a `Threaded` object into a thread to store data) should be used instead.
