### ISSUE TITLE
Segfault at reading closure from static property

### ISSUE THREAD

**Issue by SirSnyder** [krakjoe/pthreads#673]
Environment
==========

  * PHP: 7.1.2 dev
  * pthreads: 3.1.7 dev
  * OS: Debian 3.2.68 x64

Reproducing Code
==============

```
class Test extends Threaded
{
    public static $share;
}
Test::$share = new Threaded();

$objThread = new class extends Thread
{
    public function run()
    {
        Test::$share[] = function ()
        {
            echo 'running closure'. PHP_EOL;
        };
    }
};
$objThread->start();

while(Test::$share->count() === 0) {}

$closure = Test::$share[Test::$share->count() - 1];
$closure();

$objThread->join();
 ```
Expected Output
=============

no segfault

Actual Output
============

segfault

[coredump.txt](https://github.com/krakjoe/pthreads/files/753400/coredump.txt)

**Comment by tpunt** [comment]
I cannot see a simple fix to this. Whether the property is static or an array isn't relevant. The problem is with the separate thread creating the anonymous function, then shutting down (subsequently freeing it), and then the parent thread attempting to access this anonymous function. A simpler reproducing scenario would be:
```php
$objThread = new class extends Thread {
    public function run()
    {
        $this->func = function () {};
    }
};
$objThread->start() && $objThread->join();
var_dump($objThread->func);
```

I initially tried to nullify the closure's function name when copying it, since it isn't really used anyway. The script still segfaulted later on because the literals and opcodes from the function's op_array have already been freed. Allocating them via the system's allocator fixed that problem, but it still segfaulted on shutdown of the parent thread (heap corruption in ZMM) due to the runtime cache for the function being repopulated... Even if that part did work, the [destroy_op_array](https://php-lxr.adamharvey.name/source/xref/PHP-7.1/Zend/zend_opcode.c#361) function frees the literals and opcodes via ZMM's deallocator, so there'd still be problems later on due to using the system's allocator previously...

**Comment by SirSnyder** [comment]
Thanks for the detailed explanation @tpunt. My assumption was that memory will be freed with a join() call and not earlier. I'm fine with the behavior, will find another way.

**Comment by krakjoe** [comment]
Synchronization is the answer here:

	<?php
	$objThread = new class extends Thread {

		public function run()
		{
		    $this->func = function () {};

			/* notify waiter that the function is ready for execution */
			$this->notifyFunctionReady();

			/* wait for the function to be executed */
			$this->waitForExecutor();
		}

		public function waitForFunction() {
			return $this->synchronized(function(){
				while (!$this->ready) {
					$this->wait();
				}
				return true;
			});
		}

		public function notifyFunctionExecuted() {
			return $this->synchronized(function(){
				$this->executed = true;
				return $this->notify();
			});
		}

		private function notifyFunctionReady() {
			return $this->synchronized(function(){
				$this->ready = true;
				return $this->notify();
			});
		}

		private function waitForExecutor() {
			return $this->synchronized(function(){
				while (!$this->executed) {
					$this->wait();
				}
				return true;
			});
		}

		private $executed = false;
		private $ready    = false;
	};

	$objThread->start();

	$objThread->waitForFunction();

	var_dump($objThread->func);

	$objThread->notifyFunctionExecuted();

	$objThread->join();

There is no workaround to be had, when you access an object that is destroyed, and that was created by pthreads, we throw an exception, unfortunately we cannot do the same thing for objects that were not created by pthreads (closures) without overloading performance sensitive parts of the engine.

If this is a pattern you use a lot, it's conceivable that you could wrap shared closures in a `Threaded` object and implement the appropriate guarding and synchronization to make it look much nicer in the real world.
