### ISSUE TITLE
Why pthreads, if there is libuv thread pool work scheduling?

### ISSUE THREAD

**Issue by uasan** [krakjoe/pthreads#705]
With all due respect to your work, but it is better to implement `libuv` in PHP core.
The 80% web tasks is solved async in one PHP process.
The remaining 20% can run in thread pool from `libuv`

Thread pool work scheduling:
http://docs.libuv.org/en/v1.x/guide/threads.html#id1

I'm not a troll, I just want to note that other Node.js, Python, etc use `libuv`.
Well, in PHP there experimental wraper `libuv` module, welcome to testing:
https://github.com/bwoebi/php-uv

**Comment by tpunt** [comment]
PHP isn't just used for the web, and the tasks it encounters aren't always IO-bound either. CPU-bound tasks that exploit threads can be parallelised, speeding up execution time. That's why pthreads exists.

> With all due respect to your work, but it is better to implement `libuv` in PHP core.

Everything in PHP is blocking. It would take a ridiculous amount of effort to rewrite everything to use the evented layer of an OS, even with using the libuv library. That's why you haven't seen this supported natively in PHP (perhaps this is something that will change when (if) asynchronous primitives are introduced into the language).

> Well, in PHP there experimental wraper `libuv` module

Yes, there is a wrapper for the libuv library. It is also incredibly ugly to use, given that the API is basically a direct mirror of the underlying C API.

You seem to be under the misconception that internals developers aren't already aware of this stuff...

**Comment by uasan** [comment]
> PHP isn't just used for the web, and the tasks it encounters aren't always IO-bound either. CPU-bound tasks that exploit threads can be parallelised, speeding up execution time. That's why pthreads exists.

Thread pool implementation in `libuv`:
http://docs.libuv.org/en/v1.x/threadpool.html

Thread pool implementation in `php-uv`:
```PHP
<?php

$loop  = uv_default_loop();

$thread = function()
{
	echo "THREAD-CALL\n";
};

$after = function()
{
	echo "THREAD-CALL-AFTER\n";
};

for($i = 0; $i < 4; $i++)
{
	uv_queue_work($loop, $thread, $after);
}

uv_run($loop);
```

> Everything in PHP is blocking. It would take a ridiculous amount of effort to rewrite everything to use the evented layer of an OS, even with using the libuv library. That's why you haven't seen this supported natively in PHP (perhaps this is something that will change when (if) asynchronous primitives are introduced into the language).

This is all already in implementation libuv - is cross-platform and asynchronous.
File system operations:
http://docs.libuv.org/en/v1.x/fs.html#api

**Comment by tpunt** [comment]
> Thread pool implementation in `libuv`:

I know libuv has a thread pool. pthreads provides a far more flexible solution than this.

> This is all already in implementation libuv - is cross-platform and asynchronous.

I know what libuv is and what it does. As I said above, anything that currently blocks in PHP (which is basically everything) will need to be rewritten to be non-blocking using the libuv API. This is the non-trivial and time consuming part of this endeavour.

**Comment by uasan** [comment]
I think that more rational making Pthreads as simple wrapper for libuv threads, it would make it easier and more benefits in general for async evolution PHP core.

Thank.

**Comment by ClosetMonkey** [comment]
Much like asking why to Boost would make a boost:thread when boost::asio is so awesome.

**Comment by uasan** [comment]
> Much like asking why to Boost would make a boost:thread when boost::asio is so awesome.

In `boost::asio` no threads, on this need `boost:thread`
In `libuv` there are flows from the box and tools for working with threads
http://docs.libuv.org/en/v1.x/threading.html#api

Just need is wrapper in PHP for `libuv threads api`

**Comment by ClosetMonkey** [comment]
https://www.packtpub.com/books/content/task-execution-asio
