### ISSUE TITLE
Replacing the Thread::kill method ?

### ISSUE THREAD

**Issue by jerome-amp** [krakjoe/pthreads#708]
Hi, First i'm sorry to open an issue for that, i just have one question.

I try to make a timeout system on my threads to stop them after x seconds of working but i saw that the Thread::kill method is no more available in v3 API.

I just try to unset targeted object but it don't seems to work.

Do you have any solution to stop a thread during it run time ?

Thanks in advance.

PS : I love your work on pthread it's definitivly one of the best thing i've ever seen on PHP ! Congrats

**Comment by tpunt** [comment]
The method was removed because it was not safe to perform.

The typical way to perform a controlled shutdown of a thread after some time is to use a loop inside of that thread, and then break out of that loop when a certain condition has been set (typically using a property on the `Threaded` object). This enables the thread to finish executing, which can then be joined for a safe shutdown. Without knowing more about what you're trying to do, though, I cannot really give any specific advice.

Also, please keep generic questions about pthreads to StackOverflow :)
