### ISSUE TITLE
I can't install this stuff!

### ISSUE THREAD

**Issue by kovoliver** [krakjoe/pthreads#723]
Hi,
First thing first, I think it's a very good extension, but I can't use it! :)  
I have a WAMP64 server, and I tried to install this stuff. I downloaded a thread safe php version, copied the dll files  in php, php/ext and windows/system32 libraries. I added the followed line to the php.ini file:
 extension=php_pthreads.dll
But it didn't worked for me. The error message is this:
"Fatal error: Uncaught Error: Class 'Thread' not found in..."
I'm sure I messed up something but I don't know what. 

My php version is 7.1.7, the thread safety mode is enabled I followed this instructions, but I always get the same error message above. 
What can I do? 

I apologize my stupid question! :)

**Comment by tpunt** [comment]
There could be a couple of things wrong, including:
 - wrong file path to the dll (see the `extension_dir` ini setting)
 - the php.ini file isn't being used by your PHP binary (you can see this information via `php --ini`)

If possible, it may be better to use a beta version of PHP 7.2, since ZTS mode isn't safe in PHP 7.0 and 7.1.

--

Closing this because generic questions should be kept to StackOverflow.
