### ISSUE TITLE
Help for compiling

### ISSUE THREAD

**Issue by PokeyvalGamer** [krakjoe/pthreads#737]
Help me please.
Console logs : https://pastebin.com/6m3BNHYu

**Comment by tpunt** [comment]
You didn't say what version of PHP you're compiling pthreads against. In any case, pthreads is now only compatible with PHP 7.2+, and there is no stable release of pthreads for this version yet. This means you will need to build pthreads from source using the master branch of this repo against a supported version of PHP.

Closing because these types of questions belong on StackOverflow.
