### ISSUE TITLE
pthreads for PHP7.0 x64 TS

### ISSUE THREAD

**Issue by snowleopard24** [krakjoe/pthreads#739]
I'm trying to move my project from 32-bit apache, php5 and pthreads v2 windows environment to a 64-bit Apache & php7, pthreads v3 windows environment. Currently I'm exploring with php 7.0.22 but would like to go with latest php, which now is 7.1.8. I'm getting errors when using pthreads with my new environment.

When I use 64-bit version of pthreads(3.1.6) from http://windows.php.net/downloads/pecl/releases/pthreads/3.1.6/ I get errors as below:
PHP Fatal error:  The apache2handler SAPI is not supported by pthreads in Unknown on line 0
PHP Fatal error:  Unable to start pthreads module in Unknown on line 0

When I use 64-bit version of pthreads(3.0.1) from 
http://windows.php.net/downloads/pecl/releases/pthreads/3.0.1/ I get errors as below:
PHP Warning:  PHP Startup: pthreads: Unable to initialize module\nModule compiled with module API=20141001 
PHP    compiled with module API=20151012
These options need to match in Unknown on line 0

I see that you have mentioned that pthreads is only supporting php 7.2+ but I don't see any php 7.2+ release on http://windows.php.net/download#php-7.1

pthreads has really helped us in our distributed environment and we can't do without it and since Kohana is dead I'm moving to koseven which only supports php7. So, here I'm in need of a supportable pthreads for any version of php7. I'm open to moving to any version of php7 as long as I get a compatible pthreads.
I believe this is not a pthreads issue but I thought this to be the best possible way to reach out to you @krakjoe. Thanks for all the work you did on pthreads. It has helped us immensely.

**Comment by tpunt** [comment]
> PHP Fatal error: The apache2handler SAPI is not supported by pthreads in Unknown on line 0

Pthreads cannot be used in a web server environment in v3. It was never safe nor suitable to do so in any version of pthreads, but this advice has now been enforced in v3 to output an error.

> PHP Warning: PHP Startup: pthreads: Unable to initialize module\nModule compiled with module API=20141001
PHP compiled with module API=20151012

This means you compiled the wrong version of pthreads with the current PHP installation on your machine.

> I see that you have mentioned that pthreads is only supporting php 7.2+ but I don't see any php 7.2+ release on http://windows.php.net/download#php-7.1

PHP 7.0 and PHP 7.1 had problems with their ZTS mode that caused race conditions between threads (resulting in random segfaults). Support for these versions has therefore been dropped (the last stable release of pthreads (v3.1.6) was compatible with PHP 7.0, and the last commit that was compatible with PHP 7.1 was 527286336ffcf5fffb285f1bfeb100bb8bf5ec32).

In order to use pthreads with PHP 7.2 currently, the master branch of pthreads needs to be used. I'm not sure when a stable release of pthreads for this version will be made, since work is still on-going for sockets support in master.

**Comment by tpunt** [comment]
Also see the related issue #721.

**Comment by snowleopard24** [comment]
Thanks @tpunt for answering this so promptly. Just an FYI, I'm using PHP CLI in my environment.
Also, I see that php 7.2.0 beta 3 is out there and RC1 is scheduled for August 31, 2017. And, since @krakjoe is working on php 7.2, I assume release of pthreads supporting php 7.2 will come after that. Shall I then wait for php7.2 to be released before working on the migration? 
I did not compile any pthreads myself just used the available v3 versions out there on - http://windows.php.net/downloads/pecl/releases/pthreads/. Who do I reach out to if I need pthreads compiled for a php version, say 7.0.22? I guess this is a moot point since support for pthreads is dropped for php7.0 & 7.1 but still a valid question for other supportable version.

**Comment by tpunt** [comment]
> I assume release of pthreads supporting php 7.2 will come after that. 

I'm not entirely sure when the next release will be made. Hopefully this will become clearer in the coming weeks.

> Shall I then wait for php7.2 to be released before working on the migration?

That's up to you. If you are able to acquire a build of pthreads before this, then go for it.

> Who do I reach out to if I need pthreads compiled for a php version, say 7.0.22?

The last official pthreads release supported PHP 7.0.x. Whilst it will not contain any of the new bug fixes in the master branch, there's not a lot that can be done about that since pthreads is no longer supporting < PHP 7.2.

Given that your problem is already being tracked in issue #721, I'm going to close this so that we can keep the conversation on this problem in one place. Thanks.

**Comment by SirSnyder** [comment]
@tpunt do you know the open (socket) TODOs to get pthreads ready for PHP 7.2?

**Comment by tpunt** [comment]
@SirSnyder Unfortunately, I don't. I'll speak with Joe and see what else still needs to be done.

**Comment by tpunt** [comment]
@SirSnyder By the sounds of it, the socket feature is basically finished. Looking through pthreads' test suite, however, I don't see many (any) tests for it. So perhaps that's something that can be worked on.

**Comment by snowleopard24** [comment]
@tpunt Any update on when the pthreads for PHP 7.2 will be ready?

**Comment by tpunt** [comment]
@snowleopard24 Hopefully before PHP 7.2 is released (end of November).
