### ISSUE TITLE
Threads destroy array data

### ISSUE THREAD

**Issue by JohnBakery** [krakjoe/pthreads#749]
Environment
==========

  * PHP:  7.0.22
  * pthreads: 3.1.6
  * OS: Windows 10 64-bit

Summary
======

For some reason I threads keep on deleting results stored in an array. If I switch to string, I do not lose any data. Is there a way to keep arrays working?

Reproducing Code
==============

    $threadCount = 1;

    $ids = array_chunk(range(1,2000), $threadCount);

    class WorkerThreads extends Thread {
        private $threadName, $id, $result;
        
        public function __construct($threadName,$id) {
            $this->threadName = $threadName;
            $this->id = $id;
            $this->result = [];
        }

        public function run() {
            if ($this->threadName && $this->id) {
                printf('%sLoading URL #: %s' . "\n", $this->threadName, $this->id);
                $this->result = send_request($this->id);
            }
        }
    }

    while(count($ids)){
        $idList = array_shift($ids);
        $workers = [];
        foreach (range(0,count($idList)-1) as $i) {
            $threadName = "Thread #".$i.": ";
            $workers[$i] = new WorkerThreads($threadName,$idList[$i]);
            $workers[$i]->start();
        }

        foreach (range(0,count($idList)-1) as $i) {
            $workers[$i]->join();
               print_r($workers[$i]);
               exit();
            echo $workers[$i]['threadName']."Result for URL #: ".$workers[$i]['id']."\n";
        }
    }

    function send_request($id){
        $url = 'https://www.example.tld/?id='.$id;
        $response = file_get_contents($url);
        $result[] = $response;
        return $result;
    }

Expected Output
=============

WorkerThreads Object
(
    [threadName] => Thread #0:
    [id] => 1
    [result] => Array ( [0] => data )
)

Actual Output
============

PHP Fatal error:  Uncaught RuntimeException: pthreads detected an attempt to connect to an object which has already been destroyed

**Comment by tpunt** [comment]
I get a different error to you:
> PHP Fatal error:  Uncaught RuntimeException: Threaded members previously set to Threaded objects are immutable, cannot overwrite result in /Users/tpunt/prog/php/pthreads/ex.php:19

The above error (and potentially your problem) is caused by the assigning of the result of `send_request` inside of a new thread. Since this function returns an array, this array will be casted to a `Volatile` object, which will be attached to the context of the new thread. Therefore, attempting to access this data from outside of that thread will show the above error.

The fix is as follows:
```diff
@@ WorkerThreads::run @@
-$this->result = send_request($this->id);
+$this->result[] = send_request($this->id);

@@ send_request @@
-$result[] = $response;
-return $result;
+return $response;
```

So instead of creating a new array for the `WorkerThreads::$result` property inside of `WorkerThreads::run`, simply push elements to it instead.

Also, please keep such questions to StackOverflow.

**Comment by JohnBakery** [comment]
@tpunt I did post on Stack, but received no replies. The example I posted is a simplified version of my code. In my original code the `send_request` function also processes the data and returns it in an array. I just don't understand why the thread that calls the function loses the array results? Any solutions for making it work with the arrays or is converting the array to json the only way to do it?

**Comment by tpunt** [comment]
> I just don't understand why the thread that calls the function loses the array results?

It doesn't *lose* the array result, it *coerces* the array result to a `Volatile` object. This object is a `Threaded` object, and so it becomes tied to the thread that creates it. This means that once the thread that created this `Volatile` object is destroyed, then it will also be destroyed. (This is one of the hacks pthreads has to employ in order to attempt to work more safely in a seamless way.)

Another solution would be to cast the return value of `send_request` to actually be an array:
```diff
@@ WorkerThreads::__construct @@
-$this->result = [];

@@ WorkerThreads::run @@
-$this->result = send_request($this->id);
+$this->result = (array)send_request($this->id);
```

The initialisation of `WorkerThreads::$result` must also be deleted since we are directly overwriting that property. This is because of the new immutability semantics in pthreads v3, where we will violate them if we attempt to overwrite this property (since it is a `Threaded` (`Volatile`) property of a `Threaded` (non-`Volatile`) object).
