### ISSUE TITLE
Fatal error: Class 'Thread' not found in E:\www\projectname\www\thread.php on line 2

### ISSUE THREAD

**Issue by OliverLeitner** [krakjoe/pthreads#752]
i am having a problem while trying to run pthreads in xampp on windows 7.

i followed the instructions in your README.MD and i am getting the above error output from the following script after loading the module (no errors in phpinfo output, though its not showing up like for example sqlsrv...)

```
<?php
class AsyncOperation extends Thread
{
    public function __construct($arg)
    {
        $this->arg = $arg;
    }

    public function run()
    {
        if ($this->arg) {
            for ($i = 0; $i < 5; $i++) {
                echo "-> " . $this->arg . "\n";
                sleep(1);
            }
        }
    }
}
 
 flush();
 $thread = new AsyncOperation("Thread 1");
 $thread2 = new AsyncOperation("Thread 2");
 $thread->start();
 $thread2->start();
 $thread->join();
 $thread2->join();
```
i have tried with xampp php7 module and php7 fastcgi call, both give the same result...

server data:
```
PHP Version 7.1.6
system: Windows NT W720160223 6.1 build 7601 (Windows 7 Professional Edition Service Pack 1) i586 
xampp compiler: MSVC14 (Visual C++ 2015)
arch: x86
module: php_pthreads-3.1.6-7.0-ts-vc14-x86.zip
```

thanks in advance for any tip on how to get that running...

**Comment by JohnBakery** [comment]
Your PHP version is 7.1.6, pthreads driver you are using is for PHP 7.0.*. However, I think you are not even loading the driver at all, since the wrong version throws a different error.
Check your driver placements
pthreadVC2.dll should be in `xampp\php` folder
php_pthreads.dll should be in `xampp\php\ext` folder
If you are not using Apache, add `extension=php_pthreads.dll` to the php.ini. If you plan on using Apache for other purposes, create a copy of php.ini with the name php-cli.ini and add the extension line to it.

**Comment by tpunt** [comment]
^As above. Please also keep such questions to StackOverflow.

**Comment by OliverLeitner** [comment]
all the above i had already done.

it might be that im on php 7.1

so theres no support for 7.1 yet, ok.

tpunt: guess where i looked first.

**Comment by tpunt** [comment]
> so theres no support for 7.1 yet, ok.

There will not be any future support for PHP 7.1 either. Pthreads supports PHP 7.2+ only.

**Comment by OliverLeitner** [comment]
ok, so there wont be thread support for php in current xampp for the forseeable future.

well, back to python then...
