### ISSUE TITLE
PHP 7.0.15

### ISSUE THREAD

**Issue by Hodor228** [krakjoe/pthreads#754]
How to run on PHP 7.0.15 zts pthreads? I got error after make && make install:
git clone https://github.com/krakjoe/pthreads -b master pthreads

cd php-src/ext/pthreads*

/etc/php7/bin/phpize

./configure --prefix=/etc/php7 --with-libdir=/lib/x86_64-linux-gnu --enable-pthreads=shared --with-php-config=/etc/php7/bin/php-config

make && make install

**Comment by tpunt** [comment]
The master branch is only compatible with PHP 7.2+. The last release (v3.1.6) was compatible with PHP 7.0, so you will need to checkout that release.

It's also worth mentioning that ZTS mode in PHP is not safe in PHP 7.0 and 7.1. You may experience random segfaults if you use pthreads on these versions (which is why they are no longer supported).

**Comment by Hodor228** [comment]
For PHP 7.2 all installed without errors but 7.0 i got an error :(

**Comment by tpunt** [comment]
If you checked out the correct commit (739f08968af6f5b496720641ebd6e97a1b243051), then it should have built fine on PHP 7.0. If it didn't (for whatever reason), then there's not a lot I can do about it, since we are no longer supporting 7.0.
