### ISSUE TITLE
Missing Interfaces of Threaded class

### ISSUE THREAD

**Issue by eternalharvest** [krakjoe/pthreads#758]
Environment
==========

  * PHP 7.0.21 (cli) (built: Jul 27 2017 00:52:39) ( ZTS )
  * pthreads: Version 3.1.6
  * OS: Ubuntu 16.04 LTS x86_64

Summary
======
According to the document [^1] `Threaded` class implements `Traversable`, `ArrayAccess`, `Countable` interfaces. But it seems that actual `Threaded` class in my environment only implements `Traversable` interface only. 

[^1]: [The Threaded class](http://php.net/manual/en/class.threaded.php)

Reproducing Code
==============

```php
<?php

$reflect = new ReflectionClass("Threaded");

if($reflect->implementsInterface("Traversable")){
  echo "Traversable".PHP_EOL;
}

if($reflect->implementsInterface("ArrayAccess")){
  echo "ArrayAccess".PHP_EOL;
}

if($reflect->implementsInterface("Countable")){
  echo "Countable".PHP_EOL;
}
```

Expected Output
=============
```
Traversable
ArrayAccess
Countable
```

Actual Output
============
```
Traversable
```

**Comment by tpunt** [comment]
This is intentional. `ArrayAccess` and `Countable` are user land interfaces. Internal classes do not need to implement these interfaces in order to enable for such functionality. Other than being superfluous, they will also pollute the public API for `Threaded` objects with 5 additional (and completely unnecessary) methods (`offsetExists`, `offsetGet`, `offsetSet`, `offsetUnset` for `ArrayAccess`, and `count` for `Countable`).
