### ISSUE TITLE
Class 'Thread' not found

### ISSUE THREAD

**Issue by mlosh** [krakjoe/pthreads#768]
*If you know how to write phpt tests, please open a PR with environment information, and your test, this will cause CI to test your issue before a human is able to look*

Environment
==========

  * PHP: 7.0.24 *can be obtained with ```php -v```*
  * pthreads: 3.1.6 *can be obtained with ```php -dextension=pthreads.so --ri pthreads | grep Version```*
  * OS: Mac OS High Sierra*if Windows, include arch*

Summary
======
I installed pthreads using Homebrew, I'm using XAMPP and I added extension=pthreads.so in my php.ini file, restarted server but still it says that class 'Thread' is not found

**Comment by tpunt** [comment]
Pthreads seems to load fine for you in the CLI SAPI, since you've managed to acquire the version of it being used. It looks to me like you are trying to load pthreads in PHP's Apache SAPI (which will not work, since pthreads is disabled in web server SAPIs). So nothing unexpected here.

Please also keep such questions to StackOverflow. The issue tracker here is specifically for bugs in pthreads.
