### ISSUE TITLE
Pass variables by reference

### ISSUE THREAD

**Issue by luizguilhermefr** [krakjoe/pthreads#786]
Environment
==========

  * PHP:
```
PHP 7.0.26 (cli) (built: Dec  6 2017 08:33:17) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```

  * pthreads: 

```
Version => 3.1.6
```

  * OS: 

```
Linux Mint x64
```

Summary
======

Is possible to pass variables by reference to a Thread?

Reproducing Code
==============

I want to put multiple Thread workers to make math with matrices. However, if I pass the matrices to each thread by value, the exchange overhead is so killer that makes more efficient without threads.

So, my try was:

```php
// caller thread
$matrix = [];
$threads = [];
for ($i = 0; $i < $size; $i++) $matrix[$i] = [];
for ($i = 0; $i < $numThreads; $i++) $threads[] = new ThreadedClass($desiredLineSize);
for ($i = 0; $i < $size; $i++) $threads[$i % $numThreads]->pushSomeLineToWorkIn($matrix[$i]);
for ($i = 0; $i < $numThreads; $i++) $threads[$i]->start();
for ($i = 0; $i < $numThreads; $i++) $threads[$i]->join();
```

This code is intended to initialize a matrix with random values.

```php
// called thread
$works = [];
public function pushWork(&$line) { // reference operator
    $this->works[] = $line;
}
public function run() {
    for ($i = 0; $i < count($this->works); $i++) {
        for ($j = 0; $j < $this->desiredLineSize; $j++) {
            $this->works[$i][$j] = rand(1, 100);
        }
    }
}
```

Expected Output
=============

The expected output is to have a matrix properly initialized by the thread with random values.

Actual Output
============

The actual output is an empty matrix.

**Comment by tpunt** [comment]
This is not possible. The copying is required, not because of the by-value passing semantics (though modifying the matrix later on would cause a copy anyway), but because of the serialisation requirement of all property values (to enable for `Threaded` objects to work safely in a multithreaded context).

**Comment by luizguilhermefr** [comment]
Then, what is the appropriate method to deal with matrices without the
overhead of continuous memory reallocation?

Em 8 de dez de 2017 5:44 PM, "Thomas Punt" <notifications@github.com>
escreveu:

**Comment by tpunt** [comment]
Without seeing a complete version of your code, it's difficult to say. I could recommend that using `Threaded` objects, rather than arrays (which are implicitly casted to `Volatile` objects) would be more performant due to their immutability semantics (assuming you can adhere to this). But I'd need to see a complete example to provide further advice.

**Comment by luizguilhermefr** [comment]
Thank you very much for the explanation.
