### ISSUE TITLE
Completely stuck - PHP 7.2 Windows PECL - spprintf error

### ISSUE THREAD

**Issue by Teneobelgium** [krakjoe/pthreads#787]
Environment
==========

  * PHP:  7.2.0 - ZTS MSVC15 X64
  * pthreads: 3.1.6
  * OS: Windows Server 2016 - 6.2.9200

Summary
======
Completely stuck, no matter what I try, when I add the extension=php_pthreads.dll and restart
apache webserver, I execute some PHP CLI command I get an error.

Reproducing Code
==============

CLI run ANY PHP command , for example php -v

Expected Output
=============
I expect no errors
 
Actual Output
=============
**The proedure entry point spprintf could not be located in the dynamic link library c:\php\ext\php_pthreads.dll**

I already double checked to make sure I download the PECL 3.1.6 for Thread Safe X64

**Comment by tpunt** [comment]
Pthreads 3.1.6 is not compatible with PHP 7.2 - only the master branch is. The issue tracking this (for Windows) is #721.

**Comment by Teneobelgium** [comment]
I'm sorry, i'm very new to this , what is a "master branch" ? I followed the link in #721 but that takes me to the download folders I already had found and downloaded ? Where can I find this "master branch" ?

**Comment by tpunt** [comment]
The master branch is the main branch of this repository that is in active development. In order to use the master branch, you will need to make a build of pthreads yourself. Given that you're on Windows, it is unlikely you will be able to do this by yourself, so you will have to follow issue #721 to see when a build is made available for Windows.
