### ISSUE TITLE
Threaded objects with defined const causing segfault/bus error.

### ISSUE THREAD

**Issue by kwhat** [krakjoe/pthreads#788]
*If you know how to write phpt tests, please open a PR with environment information, and your test, this will cause CI to test your issue before a human is able to look*

Environment
==========

  * PHP: *PHP 7.2.0 (cli)*
  * pthreads: *3.1.7dev*
  * OS: *OS X 10.11.6 and Gentoo Linux*

Summary
======
Threaded objects with defined `const` causing segfault/bus error.

Reproducing Code
==============
```
class Testing extends Threaded
{
    const MY_VAR = "Testing";

    public function run()
    {
        echo "Running...\n";
    }
}
```
Expected Output
=============

I would expect that the reproducing code would work as expected when submitted to a worker, however, it seems to produce either a segfault, or bus error: 10.  Removing the  `const MY_VAR = "Testing";` line produces the expected result.

Actual Output
============

Bus error: 10

**Comment by SirSnyder** [comment]
Please provide a complete and working example!

**Comment by dktapps** [comment]
@SirSnyder I don't know about OP, but this test case segfaults for me with commit 1a6d591d5294a279ca67dc04b66d9936f7775382 (Ubuntu 16.04.3 LTS, PHP 7.2.1)
```php
<?php


$worker = new Worker();
$worker->start(PTHREADS_INHERIT_NONE);
$worker->stack(new Testing());
$worker->shutdown();

class Testing extends Threaded
{
    const MY_VAR = "Testing";

    public function run()
    {
        echo "Running...\n";
    }
}
```
Removing the constant works correctly:
```php
<?php


$worker = new Worker();
$worker->start(PTHREADS_INHERIT_NONE);
$worker->stack(new Testing());
$worker->shutdown();

class Testing extends Threaded
{
//    const MY_VAR = "Testing";

    public function run()
    {
        echo "Running...\n";
    }
}
```

**Comment by tpunt** [comment]
This is another fix similar to 1a6d591d5294a279ca67dc04b66d9936f7775382, where the prepare.c:L95 needs to be changed with:
```diff
-rc.ce = pthreads_prepared_entry(thread, zc->ce);
+rc.ce = pthreads_prepared_entry_internal(thread, zc->ce, 0);
```

I do wonder if this is the wrong approach, though. Given that the class is currently already being prepared, if we passed around the `candidate` class entry too, then we could simply perform a lookup in the `resolve` ZG HT to see if it has already been (or is currently being) prepared.

**Comment by tpunt** [comment]
It looks like `resolve` ZG HT is not being checked in places where a class entry is being prepared. This would explain the cause of many of the infinite recursion problems. Disabling the preparation of static members looks to be one solution (as above), but I wonder if a cleaner alternative would be to just check if the class entry has been prepared or not yet.

Or another way to fix this would be to stop using the resolve HT for classes, and just insert the new (partially prepared) class into the `EG(class_table)` HT (instead of inserting it into the `resolve` HT). That's how I have solved things with the thread preparation logic in a couple of my extensions.

I'll have another look at this sometime this weekend.

**Comment by dktapps** [comment]
@tpunt I applied your fix there and experienced problems calling private methods of classes, like this one:
```
Error: "Call to private method pocketmine\network\mcpe\VerifyLoginTask::validateToken() from context 'pocketmine\network\mcpe\VerifyLoginTask'" (EXCEPTION) in "src/pocketmine/network/mcpe/VerifyLoginTask" at line 65
```
(the relevant code is [here](https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/network/mcpe/VerifyLoginTask.php) for those interested)

Without the fix, the code segfaults when running `VerifyLoginTask` due to this same stack overflow bug.

I guess this needs more investigation.

**Comment by SirSnyder** [comment]
@tpunt I like your last approach to use ```EG(class_table)``` HT and not ```resolve``` HT. Will give it a try in a separate branch.
@dktapps have time now, I'll take a look

**Comment by SirSnyder** [comment]
@dktapps could you test master with your application and when it still fails, provide a running example please?

**Comment by dktapps** [comment]
@SirSnyder seems to be working fine now, thanks!
