### ISSUE TITLE
Is the current release of this extension even work?

### ISSUE THREAD

**Issue by AdnanHussainTurki** [krakjoe/pthreads#870]
Because the current build status is at failing and I could not install this extension on my local windows machine.

**Comment by tpunt** [comment]
I think the current build status has always showed as failing because one of the tests segfaults on Travis, but I can't seem to be able to replicate it on my machine. It also looks like there's a new sockets-related test failure, but this is to be expected, since the sockets part is still under active development.

What specific problems are you having with installing pthreads? If you are using a prebuilt DLL, then you will need to make sure it is compatible for your PHP version.

**Comment by dktapps** [comment]
@tpunt the exception-handler-options test only segfaults in release mode - I tried to debug it and it doesn't reproduce in debug mode.

**Comment by SirSnyder** [comment]
Latest [v3.2.0](https://github.com/krakjoe/pthreads/releases/tag/v3.2.0) is php 7.2 compliant
