### ISSUE TITLE
Threads seem to execute sequentially rather than concurrently

### ISSUE THREAD

**Issue by CraigHarley** [krakjoe/pthreads#877]
Environment
==========

  * PHP: *can be obtained with ```php -v```*
```
PHP 7.2.6 (cli) (built: May 23 2018 20:29:41) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.0alpha1, Copyright (c) 2002-2018, by Derick Rethans
```
  * pthreads: *can be obtained with ```php -dextension=pthreads.so --ri pthreads | grep Version```*
```
Version => 3.1.7dev
```
  * OS: *if Windows, include arch*
Windows 10, 64 bit

Summary
======

According to this blog post, the results should come out in a jumbled order:
https://www.sitepoint.com/parallel-programming-pthreads-php-fundamentals/

Reproducing Code
==============
```
<?php

require_once './vendor/autoload.php';

class Task extends Threaded
{
    private $value;

    public function __construct(int $i)
    {
        $this->value = $i;
    }

    public function run()
    {
        usleep(250000);
        echo "Task: {$this->value}\n";
    }
}

$pool = new Pool(4);

for ($i = 0; $i < 15; ++$i) {
    $pool->submit(new Task($i));
}

while ($pool->collect()) ;

$pool->shutdown();
```

Run using:
`php -n -dextension=pthreads threadTest.php`

Expected Output
=============

```
Task: 2
Task: 1
Task: 0
Task: 4
Task: 3
Task: 5
Task: 6
...
```

Actual Output
============

```
Task: 0
Task: 1
Task: 2
Task: 3
Task: 4
Task: 5
Task: 6
Task: 7
Task: 8
Task: 9
Task: 10
Task: 11
Task: 12
Task: 13
Task: 14
```

**Comment by tpunt** [comment]
There is no expected output for this example, since the output will be non-deterministic. In your case, I presume you are working out of a VM with 1 core, maybe? The less cores your machine has to execute the above script on, the more likely it will end up executing sequentially. When I execute this on a VM with 1 core available, it usually shows the results sequentially also (or they're pretty close to that). But when I execute this on my main machine with 2 cores (with each core being hype threaded), the output is pretty random every time.

There will also be other things affecting thread scheduling, which will in turn affect the output of the above script (such as OS load). Overall, I wouldn't worry about this too much. It's not that you are executing on one thread only, or that you aren't achieving any concurrency (you are, since you're using multiple threads), it's just that the thread scheduling just happens to be in order.
