### ISSUE TITLE
Can not enable extension pthreads on PHP7.2.9 Windows 7 (x64)

### ISSUE THREAD

**Issue by erik404** [krakjoe/pthreads#897]
Environment
==========

  * PHP: 7.2.9
  * pthreads: PHP version according to .dll file 7.0.2.
  * OS: Windows 7 professional x64
  * WAMP:  3.1.3 64x

Summary
======
Can not succesfully load/use the pthreads extenstion on Windows 7 professional x64 using PHPv7.2.9

Reproducing Code
==============

I followed the following documentation: [pthreads.installation](http://php.net/manual/en/pthreads.installation.php)

- downloaded the latest [binaries](https://windows.php.net/downloads/pecl/releases/pthreads/3.1.6/) for x64
- added the pthreads.dll to the `ext` folder
- added the pthreadVC2.dll to the folder where `php.exe` lives
- added the location of  pthreadVC2.dll to the global PATH `G:\wamp64\bin\php\php7.2.9\pthreadVC2.dll`
- enabled the extension in the `php.ini` `extension=pthreads`

When executing `php -i:findstr "Thread"` if get `Thread Safety => enabled` as result
The global var `PHP_ZTS` is se to true 

Expected Output
=============

A working pthreads extension :)

Actual Output
============
PHP error log `[01-Sep-2018 19:12:14 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'pthreads' (tried: G:/wamp64/bin/php/php7.2.9/ext/pthreads (The specified module could not be found.), G:/wamp64/bin/php/php7.2.9/ext/php_pthreads.dll (The specified procedure could not be found.)) in Unknown on line 0`

When I open a command prompt en run `php -v` I get the following windows error prompt `The procedure entry point spprintf could not be located in the dynamic link library php7ts.dll`

**Comment by erik404** [comment]
Fixed by finding recent build of pthreads (not linked in documentation)

**Comment by dearsina** [comment]
What isn't mentioned in the documentation is that your Visual C++ distributables also need to match the version of pthreds you're downloading.

Type php -v in the command line, and you'll see what version of Visual C++ you're running. If it's MSVC15 (instead of MSVC14 as expected by the versions found in the PECL folder) , you'll need to download a bleeding edge version of pthread from here instead to make it work:

https://windows.php.net/downloads/pecl/snaps/pthreads/3.2.0/

You'll find a version for VC15 there.
